[package]
name = "adocweave-zed"
version = "0.46.0"
edition = "2021"
license = "MIT"
publish = false
repository = "https://github.com/KeishiS/adocweave"
rust-version = "1.97.1"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
sha2 = "0.11.0"
zed_extension_api = "0.7.0"
zip = { version = "=7.1.0", default-features = false, features = ["deflate-flate2-zlib-rs"] }
