// @generated by tools/generate-protocol.mjs from protocol/public-api.json; DO NOT EDIT.

use std::collections::{BTreeMap, BTreeSet};

#[derive(Clone, Copy, Debug, Default, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmSafeMode {
    Unsafe,
    Server,
    Safe,
    #[default]
    Secure,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmResource {
    pub source_id: String,
    pub source: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(default, rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmPreprocessOptions {
    pub base_uri: Option<String>,
    pub safe_mode: WasmSafeMode,
    pub allowed_schemes: BTreeSet<String>,
    pub attributes: BTreeMap<String, Option<String>>,
    pub enable_includes: bool,
    pub max_include_depth: u32,
    pub max_includes: u32,
    pub max_total_bytes: u32,
    pub max_expanded_nodes: u32,
    pub max_source_map_segments: u32,
}

impl Default for WasmPreprocessOptions {
    fn default() -> Self {
        Self {
            base_uri: None,
            safe_mode: WasmSafeMode::Secure,
            allowed_schemes: Default::default(),
            attributes: Default::default(),
            enable_includes: true,
            max_include_depth: 16,
            max_includes: 10000,
            max_total_bytes: 52428800,
            max_expanded_nodes: 1000000,
            max_source_map_segments: 1000000,
        }
    }
}

#[derive(Clone, Debug, Default, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(default, rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmAnalysisPreprocessInput {
    pub resources: BTreeMap<String, WasmResource>,
    pub options: WasmPreprocessOptions,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmPreprocessRequest {
    pub package_version: String,
    #[serde(default)]
    pub source_id: Option<String>,
    pub source: String,
    #[serde(default)]
    pub resources: BTreeMap<String, WasmResource>,
    #[serde(default)]
    pub options: WasmPreprocessOptions,
}
