// @generated by tools/generate-protocol.mjs from protocol/public-api.json; DO NOT EDIT.

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmProductSet {
    pub syntax: bool,
    pub canonical_ast: bool,
    pub html: bool,
    pub attribute_occurrences: bool,
    pub diagnostics: bool,
    pub symbols: bool,
    pub projection: bool,
}

impl Default for WasmProductSet {
    fn default() -> Self {
        let products = adocweave::ProductSet::browser_default();
        Self {
            syntax: products.syntax,
            canonical_ast: products.canonical_ast,
            html: products.html,
            attribute_occurrences: products.attribute_occurrences,
            diagnostics: products.diagnostics,
            symbols: products.symbols,
            projection: products.projection,
        }
    }
}

impl From<WasmProductSet> for adocweave::ProductSet {
    fn from(value: WasmProductSet) -> Self {
        Self {
            syntax: value.syntax,
            canonical_ast: value.canonical_ast,
            html: value.html,
            attribute_occurrences: value.attribute_occurrences,
            diagnostics: value.diagnostics,
            symbols: value.symbols,
            projection: value.projection,
        }
    }
}
