// @generated by tools/generate-protocol.mjs from protocol/public-api.json; DO NOT EDIT.

pub(crate) const MAX_SAFE_INTEGER: u64 = 9_007_199_254_740_991;

fn deserialize_optional_safe_integer<'de, D>(deserializer: D) -> Result<Option<u64>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let value = <Option<u64> as serde::Deserialize>::deserialize(deserializer)?;
    if value.is_some_and(|value| value > MAX_SAFE_INTEGER) {
        return Err(serde::de::Error::custom(
            "safe integer exceeds the JavaScript maximum",
        ));
    }
    Ok(value)
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmReferenceNotice {
    Fallback,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmReferenceFailureKind {
    MissingTarget,
    MissingAnchor,
    AmbiguousTarget,
    OutsideRoot,
    ResolverFailure,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmResourceFailureKind {
    Missing,
    OutsideRoot,
    SchemeDenied,
    PermissionDenied,
    MediaTypeUnavailable,
    ResolverFailure,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(
    tag = "status",
    rename_all = "kebab-case",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum WasmReferenceOutcome {
    Resolved {
        href: String,
        #[serde(default)]
        display_text: Option<String>,
        #[serde(default)]
        notices: Vec<WasmReferenceNotice>,
    },
    Failed {
        kind: WasmReferenceFailureKind,
    },
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(
    tag = "status",
    rename_all = "kebab-case",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum WasmResourceOutcome {
    Resolved {
        href: String,
        media_type: String,
        #[serde(default, deserialize_with = "deserialize_optional_safe_integer")]
        byte_length: Option<u64>,
    },
    Failed {
        kind: WasmResourceFailureKind,
    },
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(
    tag = "status",
    rename_all = "kebab-case",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum WasmCitationOutcome {
    Resolved {
        #[serde(default)]
        segments: Vec<WasmCitationSegment>,
    },
    Failed {
        kind: WasmReferenceFailureKind,
    },
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmCitationSegment {
    pub text: String,
    #[serde(default)]
    pub anchor: Option<String>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmGeneratedBibliographyEntry {
    pub citation_key: String,
    pub text: String,
    #[serde(default)]
    pub label: Option<String>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmGeneratedBibliography {
    pub title: String,
    #[serde(default)]
    pub entries: Vec<WasmGeneratedBibliographyEntry>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmResolvedCitation {
    pub source_start: u32,
    pub source_end: u32,
    pub outcome: WasmCitationOutcome,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmResolvedReference {
    pub source_start: u32,
    pub source_end: u32,
    pub outcome: WasmReferenceOutcome,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmResolvedResource {
    pub source_start: u32,
    pub source_end: u32,
    pub outcome: WasmResourceOutcome,
}

#[derive(Clone, Debug, Default, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(default, rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmRenderInputs {
    #[serde(default)]
    pub references: Vec<WasmResolvedReference>,
    #[serde(default)]
    pub resources: Vec<WasmResolvedResource>,
    #[serde(default)]
    pub citations: Vec<WasmResolvedCitation>,
    #[serde(default)]
    pub generated_bibliography: Option<WasmGeneratedBibliography>,
}
