// @generated by tools/generate-protocol.mjs from protocol/public-api.json; DO NOT EDIT.

use crate::{WasmMathLanguage, WasmProductSet, WasmSeverity};

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmResponse {
    pub package_version: String,
    pub version: u32,
    pub generation: u32,
    pub products: WasmProductSet,
    pub parse: ParseSummary,
    pub syntax: String,
    pub ast: String,
    pub html: String,
    pub attribute_occurrences: Vec<WasmDocumentAttributeOccurrence>,
    pub attribute_queries: WasmAttributeQueryProduct,
    pub resource_queries: Vec<WasmResourceQuery>,
    pub diagnostics: Vec<WasmDiagnostic>,
    pub render_diagnostics: Vec<WasmDiagnostic>,
    pub symbols: Vec<WasmDocumentSymbol>,
    pub projection: Option<WasmDocumentProjection>,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmApplicability {
    Always,
    Maybe,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmAttributeBindingQuery {
    pub id: u32,
    pub source_id: Option<String>,
    pub operation: WasmDocumentAttributeOperation,
    pub effective_value: Option<String>,
    pub error: Option<WasmAttributeExpansionError>,
    pub occurrence: WasmDocumentAttributeOccurrence,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmAttributeExpansionError {
    Undefined,
    Cycle,
    DepthLimitExceeded,
    SizeLimitExceeded,
}

#[derive(Clone, Debug, Default, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmAttributeQueryProduct {
    pub bindings: Vec<WasmAttributeBindingQuery>,
    pub references: Vec<WasmAttributeReferenceQuery>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmAttributeReferenceQuery {
    pub source_id: Option<String>,
    pub range: WasmTextRange,
    pub name_range: WasmTextRange,
    pub name: String,
    pub binding_id: Option<u32>,
    pub effective_value: Option<String>,
    pub error: Option<WasmAttributeExpansionError>,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmAttributeValueContinuation {
    Soft,
    Hard,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmBibliographyEntry {
    pub id: String,
    pub label: Option<String>,
    pub definition_range: WasmTextRange,
    pub references: Vec<WasmTextRange>,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmBlockPresentationKind {
    Admonition,
    Quote,
    Verse,
    Example,
    Sidebar,
    Open,
    Collapsible,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmBlockPresentationProjection {
    pub kind: WasmBlockPresentationKind,
    pub source_range: WasmTextRange,
    pub content_range: WasmTextRange,
    pub title: Option<String>,
    pub attribution: Option<String>,
    pub citation: Option<String>,
    pub roles: Vec<String>,
    pub open: Option<bool>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmCitationAttributeProjection {
    pub source_range: WasmTextRange,
    pub name: Option<String>,
    pub value: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmCitationKeyProjection {
    pub source_range: WasmTextRange,
    pub key: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmCitationProjection {
    pub order: u32,
    pub source_range: WasmTextRange,
    pub keys: Vec<WasmCitationKeyProjection>,
    pub attributes: Vec<WasmCitationAttributeProjection>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmDiagnostic {
    pub id: String,
    pub code: String,
    pub severity: WasmSeverity,
    pub message: String,
    pub range: WasmTextRange,
    pub related: Vec<WasmRelatedInformation>,
    pub fixes: Vec<WasmFix>,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmDocumentAttributeContinuation {
    pub kind: WasmAttributeValueContinuation,
    pub range: WasmTextRange,
}

/// One source-preserving standard document-attribute occurrence.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmDocumentAttributeOccurrence {
    pub range: WasmTextRange,
    pub name_range: WasmTextRange,
    pub name: String,
    pub value: WasmDocumentAttributeValue,
    pub operation: WasmDocumentAttributeOperation,
    pub valid: bool,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmDocumentAttributeOperation {
    Set,
    Unset,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmDocumentAttributeValue {
    pub source_range: WasmTextRange,
    pub source_text: String,
    pub folded_text: String,
    pub lines: Vec<WasmDocumentAttributeValueLine>,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmDocumentAttributeValueLine {
    pub range: WasmTextRange,
    pub indent_range: WasmTextRange,
    pub content_range: WasmTextRange,
    pub ending_range: WasmTextRange,
    pub continuation: Option<WasmDocumentAttributeContinuation>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmDocumentCatalogs {
    pub footnotes: Vec<WasmFootnote>,
    pub bibliography: Vec<WasmBibliographyEntry>,
    pub index: Vec<WasmIndexEntry>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmDocumentProjection {
    pub source_id: Option<String>,
    pub source_blocks: Vec<WasmSourceBlockProjection>,
    pub formulas: Vec<WasmFormulaProjection>,
    pub citations: Vec<WasmCitationProjection>,
    pub block_presentations: Vec<WasmBlockPresentationProjection>,
    pub ordered_lists: Vec<WasmOrderedListProjection>,
    pub reference_edges: Vec<WasmReferenceEdge>,
    pub external_links: Vec<WasmExternalLink>,
    pub searchable_text: WasmSearchableText,
    pub structure: WasmDocumentStructure,
    pub catalogs: WasmDocumentCatalogs,
    pub targets: Vec<WasmReferenceTarget>,
    pub title: Option<WasmProjectedText>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmDocumentStructure {
    pub headings: Vec<WasmStructuredHeading>,
    pub toc: Vec<WasmTocEntry>,
    pub manpage: Option<WasmManpage>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmDocumentSymbol {
    pub name: String,
    pub kind: WasmSymbolKind,
    pub range: WasmTextRange,
    pub selection_range: WasmTextRange,
    pub children: Vec<WasmDocumentSymbol>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmExternalLink {
    pub source_range: WasmTextRange,
    pub target_range: WasmTextRange,
    pub target: String,
    pub label: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmFix {
    pub title: String,
    pub applicability: WasmApplicability,
    pub edits: Vec<WasmTextEdit>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmFootnote {
    pub number: u32,
    pub id: Option<String>,
    pub definition_range: WasmTextRange,
    pub content_range: WasmTextRange,
    pub text: String,
    pub occurrences: Vec<WasmTextRange>,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmFormulaKind {
    Inline,
    Block,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmFormulaProjection {
    pub kind: WasmFormulaKind,
    pub language: WasmMathLanguage,
    pub source_range: WasmTextRange,
    pub content_range: WasmTextRange,
    pub source: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmIndexEntry {
    pub terms: Vec<String>,
    pub display: String,
    pub occurrences: Vec<WasmTextRange>,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmMacroForm {
    Inline,
    Block,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmManpage {
    pub name: String,
    pub section: String,
    pub purpose: String,
    pub title_range: WasmTextRange,
    pub name_range: WasmTextRange,
    pub purpose_range: WasmTextRange,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmOrderedListProjection {
    pub source_range: WasmTextRange,
    pub start: Option<u32>,
    pub reversed: bool,
    pub style: WasmOrderedListStyle,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmOrderedListStyle {
    Arabic,
    Decimal,
    Loweralpha,
    Upperalpha,
    Lowerroman,
    Upperroman,
    Lowergreek,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ParseSummary {
    pub block_count: u32,
    pub node_count: u32,
    pub reference_count: u32,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmProjectedReferenceFailureKind {
    MissingReferenceTarget,
    MissingReferenceAnchor,
    AmbiguousReferenceTarget,
    ReferenceOutsideRoot,
    ReferenceResolverFailure,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmProjectedReferenceNotice {
    ReferenceResolutionFallback,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(
    tag = "status",
    rename_all = "kebab-case",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum WasmProjectedResolutionOutcome {
    Failed {
        kind: WasmProjectedReferenceFailureKind,
    },
    Resolved {
        href: String,
        display_text: Option<String>,
        notices: Vec<WasmProjectedReferenceNotice>,
    },
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmProjectedText {
    pub source_range: WasmTextRange,
    pub text: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmReferenceEdge {
    pub source_id: Option<String>,
    pub source_range: WasmTextRange,
    pub target: WasmReferenceKey,
    pub resolution: Option<WasmProjectedResolutionOutcome>,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(
    tag = "kind",
    rename_all = "kebab-case",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum WasmReferenceKey {
    Document {
        document: String,
        anchor: Option<String>,
    },
    Local {
        anchor: String,
    },
    Scheme {
        scheme: String,
        locator: String,
        anchor: Option<String>,
    },
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmReferenceTarget {
    pub kind: WasmReferenceTargetKind,
    pub id: String,
    pub label: String,
    pub id_range: WasmTextRange,
    pub target_range: WasmTextRange,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmReferenceTargetKind {
    DocumentTitle,
    Part,
    Section,
    ExplicitAnchor,
    InlineAnchor,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmRelatedInformation {
    pub range: WasmTextRange,
    pub message: String,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmResourcePurpose {
    Image,
    Icon,
    Audio,
    Video,
    VideoPoster,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmResourceQuery {
    pub purpose: WasmResourcePurpose,
    pub form: WasmMacroForm,
    pub owner_range: WasmTextRange,
    pub range: WasmTextRange,
    pub target_range: WasmTextRange,
    pub target: String,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmSearchTextKind {
    Prose,
    Code,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmSearchTextSegment {
    pub kind: WasmSearchTextKind,
    pub source_range: WasmTextRange,
    pub text: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmSearchableText {
    pub text: String,
    pub segments: Vec<WasmSearchTextSegment>,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmSectionKind {
    DocumentTitle,
    Part,
    Section,
    Appendix,
    Discrete,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmSourceBlockProjection {
    pub source_range: WasmTextRange,
    pub content_range: WasmTextRange,
    pub title: Option<WasmProjectedText>,
    pub language_range: Option<WasmTextRange>,
    pub language: Option<String>,
    pub line_numbers: bool,
    pub start_line: Option<u32>,
    pub source: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmStructuredHeading {
    pub kind: WasmSectionKind,
    pub level: u32,
    pub id: String,
    pub id_range: WasmTextRange,
    pub title: String,
    pub range: WasmTextRange,
    pub title_range: WasmTextRange,
    pub number: Vec<u32>,
    pub toc_included: bool,
}

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmSymbolKind {
    DocumentTitle,
    Part,
    Section,
    ListItem,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmTextEdit {
    pub range: WasmTextRange,
    pub replacement: String,
}

/// A half-open UTF-8 byte range in the submitted source.
#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmTextRange {
    pub start: u32,
    pub end: u32,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WasmTocEntry {
    pub id: String,
    pub title: String,
    pub level: u32,
    pub number: Vec<u32>,
    pub range: WasmTextRange,
    pub children: Vec<WasmTocEntry>,
}
