// @generated by tools/generate-protocol.mjs from protocol/public-api.json; DO NOT EDIT.

#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmMathLanguage {
    Latex,
    Typst,
}

#[derive(Clone, Copy, Debug, Default, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum WasmSeverity {
    Error,
    #[default]
    Warning,
    Information,
    Hint,
}
