// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActiveUrlOptions = { allowedSchemes?: Array<string>, allowAuthoredRelative?: boolean, allowResolvedRelative?: boolean, allowResolvedRootRelative?: boolean, allowDataUris?: boolean, };

export type AnalyzeRequest = { source: SourceInput, products: ProductRequest, resources?: ResourceInput, };

export type AnalyzeResult = { syntax?: string, canonicalAst?: string, html?: string, attributeOccurrences?: Array<DocumentAttributeOccurrence>, attributeQueries?: AttributeQueryResult, resourceQueries?: Array<ResourceQuery>, diagnostics?: Array<Diagnostic>, symbols?: Array<DocumentSymbol>, document?: DocumentView | null, };

export type Applicability = "always" | "maybe";

export type AttributeBindingQuery = { id: number, sourceId: string | null, operation: DocumentAttributeOperation, effectiveValue: string | null, error: AttributeExpansionError | null, occurrence: DocumentAttributeOccurrence, };

export type AttributeExpansionError = "undefined" | "cycle" | "depth-limit-exceeded" | "size-limit-exceeded";

export type AttributeQueryResult = { bindings: Array<AttributeBindingQuery>, references: Array<AttributeReferenceQuery>, };

export type AttributeReferenceQuery = { sourceId: string | null, range: TextRange, nameRange: TextRange, name: string, bindingId: number | null, effectiveValue: string | null, error: AttributeExpansionError | null, };

export type AttributeValueContinuation = "soft" | "hard";

export type AuthoredUrlOptions = { allowedSchemes?: Array<string>, allowRelative?: boolean, };

export type BibliographyEntry = { id: string, label: string | null, definitionRange: TextRange, references: Array<TextRange>, };

export type BlockPresentation = { kind: BlockPresentationKind, sourceRange: TextRange, contentRange: TextRange, title: string | null, attribution: string | null, citation: string | null, roles: Array<string>, open: boolean | null, caption: string | null, };

export type BlockPresentationKind = "admonition" | "quote" | "verse" | "example" | "sidebar" | "open" | "collapsible" | "figure" | "table";

export type Citation = { order: number, sourceRange: TextRange, keys: Array<CitationKey>, attributes: Array<CitationAttribute>, };

export type CitationAttribute = { sourceRange: TextRange, name: string | null, value: string, };

export type CitationKey = { sourceRange: TextRange, key: string, };

export type CitationOutcome = { "status": "resolved", segments?: Array<CitationSegment>, } | { "status": "failed", kind: ReferenceFailureKind, };

export type CitationSegment = { text: string, anchor?: string, };

export type Diagnostic = { id: string, code: string, severity: Severity, message: string, range: TextRange, related: Array<RelatedInformation>, fixes: Array<Fix>, };

export type DiagnosticOptions = { protectedAttributes?: { [key in string]: string | null }, authoredUrls?: AuthoredUrlOptions, rules?: { [key in string]: RuleOptions }, maxDiagnostics?: number, };

export type DocumentAttributeContinuation = { kind: AttributeValueContinuation, range: TextRange, };

/**
 * One source-preserving standard document-attribute occurrence.
 */
export type DocumentAttributeOccurrence = { range: TextRange, nameRange: TextRange, name: string, value: DocumentAttributeValue, operation: DocumentAttributeOperation, valid: boolean, };

export type DocumentAttributeOperation = "set" | "unset" | "counter";

export type DocumentAttributeValue = { sourceRange: TextRange, sourceText: string, foldedText: string, lines: Array<DocumentAttributeValueLine>, };

export type DocumentAttributeValueLine = { range: TextRange, indentRange: TextRange, contentRange: TextRange, endingRange: TextRange, continuation: DocumentAttributeContinuation | null, };

export type DocumentCatalogs = { footnotes: Array<Footnote>, bibliography: Array<BibliographyEntry>, index: Array<IndexEntry>, };

export type DocumentMode = "fragment" | "complete";

export type DocumentReferenceFailureKind = "missing-reference-target" | "missing-reference-anchor" | "ambiguous-reference-target" | "reference-outside-root" | "reference-resolver-failure";

export type DocumentReferenceNotice = "reference-resolution-fallback";

export type DocumentResolutionOutcome = { "status": "failed", kind: DocumentReferenceFailureKind, } | { "status": "resolved", href: string, displayText: string | null, notices: Array<DocumentReferenceNotice>, };

export type DocumentStructure = { headings: Array<StructuredHeading>, toc: Array<TocEntry>, manpage: Manpage | null, };

export type DocumentSymbol = { name: string, kind: SymbolKind, range: TextRange, selectionRange: TextRange, children: Array<DocumentSymbol>, };

export type DocumentText = { sourceRange: TextRange, text: string, };

export type DocumentView = { sourceId: string | null, sourceBlocks: Array<SourceBlock>, formulas: Array<Formula>, citations: Array<Citation>, blockPresentations: Array<BlockPresentation>, orderedLists: Array<OrderedList>, referenceEdges: Array<ReferenceEdge>, externalLinks: Array<ExternalLink>, searchableText: SearchableText, structure: DocumentStructure, catalogs: DocumentCatalogs, targets: Array<ReferenceTarget>, title: DocumentText | null, };

export type ExternalLink = { sourceRange: TextRange, targetRange: TextRange, target: string, label: string, };

export type ExternalLinkOptions = { openInNewContext?: boolean, noreferrer?: boolean, };

export type Fix = { title: string, applicability: Applicability, edits: Array<TextEdit>, };

export type Footnote = { number: number, id: string | null, definitionRange: TextRange, contentRange: TextRange, text: string, occurrences: Array<TextRange>, };

export type Formula = { kind: FormulaKind, language: MathLanguage, sourceRange: TextRange, contentRange: TextRange, source: string, };

export type FormulaKind = "inline" | "block";

export type GeneratedBibliography = { title: string, entries?: Array<GeneratedBibliographyEntry>, };

export type GeneratedBibliographyEntry = { citationKey: string, text: string, label?: string, number?: number, };

export type HtmlOptions = { documentMode?: DocumentMode, activeUrls?: ActiveUrlOptions, externalLinks?: ExternalLinkOptions, sourceLanguages?: SourceLanguageOptions, roles?: RoleOptions, mathLanguages?: Array<MathLanguage>, unresolvedReferences?: UnresolvedReferencePresentation, resourceCapabilities?: ResourceCapabilities, stylesheets?: Array<Stylesheet>, };

export type IncludeHandling = "expand" | "preserve";

export type IndexEntry = { terms: Array<string>, display: string, occurrences: Array<TextRange>, };

export type MacroForm = "inline" | "block";

export type Manpage = { name: string, section: string, purpose: string, titleRange: TextRange, nameRange: TextRange, purposeRange: TextRange, };

export type MathLanguage = "latex" | "typst";

export type OrderedList = { sourceRange: TextRange, start: number | null, reversed: boolean, style: OrderedListStyle, };

export type OrderedListStyle = "arabic" | "decimal" | "loweralpha" | "upperalpha" | "lowerroman" | "upperroman" | "lowergreek";

export type ProductRequest = { syntax?: true, canonicalAst?: true, html?: true | HtmlOptions, attributeOccurrences?: true, attributeQueries?: true, resourceQueries?: true, diagnostics?: true | DiagnosticOptions, symbols?: true, document?: true, };

export type ReferenceEdge = { sourceId: string | null, sourceRange: TextRange, target: ReferenceKey, resolution: DocumentResolutionOutcome | null, };

export type ReferenceFailureKind = "missing-target" | "missing-anchor" | "ambiguous-target" | "outside-root" | "resolver-failure";

export type ReferenceKey = { "kind": "document", document: string, anchor: string | null, } | { "kind": "local", anchor: string, } | { "kind": "scheme", scheme: string, locator: string, anchor: string | null, };

export type ReferenceNotice = "fallback";

export type ReferenceOutcome = { "status": "resolved", href: string, displayText?: string, notices?: Array<ReferenceNotice>, } | { "status": "failed", kind: ReferenceFailureKind, };

export type ReferenceTarget = { kind: ReferenceTargetKind, id: string, label: string, idRange: TextRange, targetRange: TextRange, };

export type ReferenceTargetKind = "document-title" | "part" | "section" | "explicit-anchor" | "inline-anchor";

export type RelatedInformation = { range: TextRange, message: string, };

export type ResolvedCitation = { sourceStart: number, sourceEnd: number, outcome: CitationOutcome, };

export type ResolvedReference = { sourceStart: number, sourceEnd: number, outcome: ReferenceOutcome, };

export type ResolvedResource = { sourceStart: number, sourceEnd: number, outcome: ResourceOutcome, };

export type ResourceCapabilities = { images?: boolean, media?: boolean, };

export type ResourceFailureKind = "missing" | "outside-root" | "scheme-denied" | "permission-denied" | "media-type-unavailable" | "resolver-failure";

export type ResourceInput = { documents?: { [key in string]: string }, baseUri?: string, safeMode?: SafeMode, allowedSchemes?: Array<string>, includes?: IncludeHandling, references?: Array<ResolvedReference>, assets?: Array<ResolvedResource>, citations?: Array<ResolvedCitation>, bibliography?: GeneratedBibliography | null, };

export type ResourceOutcome = { "status": "resolved", href: string, mediaType: string, byteLength?: number, } | { "status": "failed", kind: ResourceFailureKind, };

export type ResourcePurpose = "image" | "icon" | "audio" | "video" | "video-poster";

export type ResourceQuery = { purpose: ResourcePurpose, form: MacroForm, ownerRange: TextRange, range: TextRange, targetRange: TextRange, target: string, };

export type RoleOptions = { allowed?: Array<string>, unknown?: UnknownRole, };

export type RuleOptions = { enabled?: boolean, severity?: Severity, };

export type SafeMode = "unsafe" | "server" | "safe" | "secure";

export type SearchTextKind = "prose" | "code";

export type SearchTextSegment = { kind: SearchTextKind, sourceRange: TextRange, text: string, };

export type SearchableText = { text: string, segments: Array<SearchTextSegment>, };

export type SectionKind = "document-title" | "part" | "section" | "appendix" | "discrete";

export type Severity = "error" | "warning" | "information" | "hint";

export type SourceBlock = { sourceRange: TextRange, contentRange: TextRange, title: DocumentText | null, languageRange: TextRange | null, language: string | null, lineNumbers: boolean, startLine: number | null, source: string, caption: string | null, };

export type SourceInput = { text: string, id?: string, attributes?: { [key in string]: string | null }, syntaxMode?: SyntaxMode, };

export type SourceLanguageOptions = { allowed?: Array<string>, unknown?: UnknownSourceLanguage, };

export type StructuredHeading = { kind: SectionKind, level: number, id: string, idRange: TextRange, title: string, range: TextRange, titleRange: TextRange, number: Array<number>, tocIncluded: boolean, };

export type Stylesheet = { "kind": "external", url: string, } | { "kind": "inline", css: string, };

export type SymbolKind = "document-title" | "part" | "section" | "list-item";

export type SyntaxMode = "permissive" | "strict";

export type TextEdit = { range: TextRange, replacement: string, };

/**
 * A half-open UTF-8 byte range in the submitted source.
 */
export type TextRange = { start: number, end: number, };

export type TocEntry = { id: string, title: string, level: number, number: Array<number>, range: TextRange, children: Array<TocEntry>, };

export type UnknownRole = "silent" | "diagnostic";

export type UnknownSourceLanguage = "preserve-sanitized" | "omit-class" | "diagnostic";

export type UnresolvedReferencePresentation = "target" | "label-only" | "hidden";
