// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParseSummary = { blockCount: number, nodeCount: number, referenceCount: number, };

export type WasmActiveUrlPolicy = { allowedSchemes: Array<string>, allowAuthoredRelative: boolean, allowResolvedRelative: boolean, allowResolvedRootRelative: boolean, allowDataUris: boolean, };

export type WasmAnalysisOptions = { syntax: WasmSyntaxOptions, diagnostics: WasmDiagnosticProfile, attributes: { [key in string]: string | null }, };

export type WasmAnalysisPreprocessInput = { resources: { [key in string]: WasmResource }, options: WasmPreprocessOptions, };

export type WasmApplicability = "always" | "maybe";

export type WasmAttributeBindingQuery = { id: number, sourceId: string | null, operation: WasmDocumentAttributeOperation, effectiveValue: string | null, error: WasmAttributeExpansionError | null, occurrence: WasmDocumentAttributeOccurrence, };

export type WasmAttributeExpansionError = "undefined" | "cycle" | "depth-limit-exceeded" | "size-limit-exceeded";

export type WasmAttributeQueryProduct = { bindings: Array<WasmAttributeBindingQuery>, references: Array<WasmAttributeReferenceQuery>, };

export type WasmAttributeReferenceQuery = { sourceId: string | null, range: WasmTextRange, nameRange: WasmTextRange, name: string, bindingId: number | null, effectiveValue: string | null, error: WasmAttributeExpansionError | null, };

export type WasmAttributeValueContinuation = "soft" | "hard";

export type WasmAuthoredUrlPolicy = { allowedSchemes: Array<string>, allowRelative: boolean, };

export type WasmBibliographyEntry = { id: string, label: string | null, definitionRange: WasmTextRange, references: Array<WasmTextRange>, };

export type WasmBlockPresentationKind = "admonition" | "quote" | "verse" | "example" | "sidebar" | "open" | "collapsible" | "figure" | "table";

export type WasmBlockPresentationProjection = { kind: WasmBlockPresentationKind, sourceRange: WasmTextRange, contentRange: WasmTextRange, title: string | null, attribution: string | null, citation: string | null, roles: Array<string>, open: boolean | null, caption: string | null, };

export type WasmCitationAttributeProjection = { sourceRange: WasmTextRange, name: string | null, value: string, };

export type WasmCitationKeyProjection = { sourceRange: WasmTextRange, key: string, };

export type WasmCitationOutcome = { "status": "resolved", segments: Array<WasmCitationSegment>, } | { "status": "failed", kind: WasmReferenceFailureKind, };

export type WasmCitationProjection = { order: number, sourceRange: WasmTextRange, keys: Array<WasmCitationKeyProjection>, attributes: Array<WasmCitationAttributeProjection>, };

export type WasmCitationSegment = { text: string, anchor: string | null, };

export type WasmDiagnostic = { id: string, code: string, severity: WasmSeverity, message: string, range: WasmTextRange, related: Array<WasmRelatedInformation>, fixes: Array<WasmFix>, };

export type WasmDiagnosticProfile = { protectedAttributes: { [key in string]: string | null }, authoredUrls: WasmAuthoredUrlPolicy, maxDiagnostics: number, rules: { [key in string]: WasmRuleSettings }, };

export type WasmDocumentAttributeContinuation = { kind: WasmAttributeValueContinuation, range: WasmTextRange, };

/**
 * One source-preserving standard document-attribute occurrence.
 */
export type WasmDocumentAttributeOccurrence = { range: WasmTextRange, nameRange: WasmTextRange, name: string, value: WasmDocumentAttributeValue, operation: WasmDocumentAttributeOperation, valid: boolean, };

export type WasmDocumentAttributeOperation = "set" | "unset" | "counter";

export type WasmDocumentAttributeValue = { sourceRange: WasmTextRange, sourceText: string, foldedText: string, lines: Array<WasmDocumentAttributeValueLine>, };

export type WasmDocumentAttributeValueLine = { range: WasmTextRange, indentRange: WasmTextRange, contentRange: WasmTextRange, endingRange: WasmTextRange, continuation: WasmDocumentAttributeContinuation | null, };

export type WasmDocumentCatalogs = { footnotes: Array<WasmFootnote>, bibliography: Array<WasmBibliographyEntry>, index: Array<WasmIndexEntry>, };

export type WasmDocumentMode = "fragment" | "complete";

export type WasmDocumentProjection = { sourceId: string | null, sourceBlocks: Array<WasmSourceBlockProjection>, formulas: Array<WasmFormulaProjection>, citations: Array<WasmCitationProjection>, blockPresentations: Array<WasmBlockPresentationProjection>, orderedLists: Array<WasmOrderedListProjection>, referenceEdges: Array<WasmReferenceEdge>, externalLinks: Array<WasmExternalLink>, searchableText: WasmSearchableText, structure: WasmDocumentStructure, catalogs: WasmDocumentCatalogs, targets: Array<WasmReferenceTarget>, title: WasmProjectedText | null, };

export type WasmDocumentStructure = { headings: Array<WasmStructuredHeading>, toc: Array<WasmTocEntry>, manpage: WasmManpage | null, };

export type WasmDocumentSymbol = { name: string, kind: WasmSymbolKind, range: WasmTextRange, selectionRange: WasmTextRange, children: Array<WasmDocumentSymbol>, };

export type WasmError = { code: string, message: string, };

export type WasmExternalLink = { sourceRange: WasmTextRange, targetRange: WasmTextRange, target: string, label: string, };

export type WasmExternalLinkPolicy = { openInNewContext: boolean, noreferrer: boolean, };

export type WasmFix = { title: string, applicability: WasmApplicability, edits: Array<WasmTextEdit>, };

export type WasmFootnote = { number: number, id: string | null, definitionRange: WasmTextRange, contentRange: WasmTextRange, text: string, occurrences: Array<WasmTextRange>, };

export type WasmFormulaKind = "inline" | "block";

export type WasmFormulaProjection = { kind: WasmFormulaKind, language: WasmMathLanguage, sourceRange: WasmTextRange, contentRange: WasmTextRange, source: string, };

export type WasmGeneratedBibliography = { title: string, entries: Array<WasmGeneratedBibliographyEntry>, };

export type WasmGeneratedBibliographyEntry = { citationKey: string, text: string, label: string | null, number: number | null, };

export type WasmIndexEntry = { terms: Array<string>, display: string, occurrences: Array<WasmTextRange>, };

export type WasmLimits = { maxInputBytes: number, maxLineBytes: number, maxListDepth: number, maxListContinuations: number, maxBlockDepth: number, maxInlineDepth: number, maxFormulaBytes: number, maxTableBytes: number, maxTableCells: number, maxTableColumns: number, maxTableDepth: number, maxCatalogEntries: number, maxCatalogBytes: number, maxBlocks: number, maxNodes: number, maxReferences: number, maxAttributes: number, maxAttributeExpansionDepth: number, maxAttributeExpansionBytes: number, };

export type WasmMacroForm = "inline" | "block";

export type WasmManpage = { name: string, section: string, purpose: string, titleRange: WasmTextRange, nameRange: WasmTextRange, purposeRange: WasmTextRange, };

export type WasmMathLanguage = "latex" | "typst";

export type WasmOrderedListProjection = { sourceRange: WasmTextRange, start: number | null, reversed: boolean, style: WasmOrderedListStyle, };

export type WasmOrderedListStyle = "arabic" | "decimal" | "loweralpha" | "upperalpha" | "lowerroman" | "upperroman" | "lowergreek";

export type WasmOutputLimits = { maxOutputBytes: number, };

export type WasmPreprocessOptions = { baseUri: string | null, safeMode: WasmSafeMode, allowedSchemes: Array<string>, attributes: { [key in string]: string | null }, enableIncludes: boolean, maxIncludeDepth: number, maxIncludes: number, maxTotalBytes: number, maxExpandedNodes: number, maxSourceMapSegments: number, maxAttributeExpansionDepth: number, maxAttributeExpansionBytes: number, };

export type WasmPreprocessRequest = { packageVersion: string, sourceId: string | null, source: string, resources: { [key in string]: WasmResource }, options: WasmPreprocessOptions, };

export type WasmPreprocessResponse = { packageVersion: string, source: string, sourceMap: Array<WasmSourceMapSegment>, };

export type WasmProductSet = { syntax: boolean, canonicalAst: boolean, html: boolean, attributeOccurrences: boolean, attributeQueries: boolean, resourceQueries: boolean, diagnostics: boolean, symbols: boolean, projection: boolean, };

export type WasmProjectedReferenceFailureKind = "missing-reference-target" | "missing-reference-anchor" | "ambiguous-reference-target" | "reference-outside-root" | "reference-resolver-failure";

export type WasmProjectedReferenceNotice = "reference-resolution-fallback";

export type WasmProjectedResolutionOutcome = { "status": "failed", kind: WasmProjectedReferenceFailureKind, } | { "status": "resolved", href: string, displayText: string | null, notices: Array<WasmProjectedReferenceNotice>, };

export type WasmProjectedText = { sourceRange: WasmTextRange, text: string, };

export type WasmReferenceEdge = { sourceId: string | null, sourceRange: WasmTextRange, target: WasmReferenceKey, resolution: WasmProjectedResolutionOutcome | null, };

export type WasmReferenceFailureKind = "missing-target" | "missing-anchor" | "ambiguous-target" | "outside-root" | "resolver-failure";

export type WasmReferenceKey = { "kind": "document", document: string, anchor: string | null, } | { "kind": "local", anchor: string, } | { "kind": "scheme", scheme: string, locator: string, anchor: string | null, };

export type WasmReferenceNotice = "fallback";

export type WasmReferenceOutcome = { "status": "resolved", href: string, displayText: string | null, notices: Array<WasmReferenceNotice>, } | { "status": "failed", kind: WasmReferenceFailureKind, };

export type WasmReferenceTarget = { kind: WasmReferenceTargetKind, id: string, label: string, idRange: WasmTextRange, targetRange: WasmTextRange, };

export type WasmReferenceTargetKind = "document-title" | "part" | "section" | "explicit-anchor" | "inline-anchor";

export type WasmRelatedInformation = { range: WasmTextRange, message: string, };

export type WasmRenderInputs = { references: Array<WasmResolvedReference>, resources: Array<WasmResolvedResource>, citations: Array<WasmResolvedCitation>, generatedBibliography: WasmGeneratedBibliography | null, };

export type WasmRenderPolicy = { activeUrls: WasmActiveUrlPolicy, externalLinks: WasmExternalLinkPolicy, sourceLanguages: WasmSourceLanguagePolicy, roles: WasmRolePolicy, mathLanguages: Array<WasmMathLanguage>, unresolvedReferences: WasmUnresolvedReferencePresentation, resources: WasmResourceCapabilities, documentMode: WasmDocumentMode, stylesheets: Array<WasmStylesheet>, };

export type WasmRequest = { packageVersion: string, sourceId: string | null, version: number, generation: number, source: string, preprocess: WasmAnalysisPreprocessInput | null, products: WasmProductSet, renderInputs: WasmRenderInputs, analysisOptions: WasmAnalysisOptions, renderPolicy: WasmRenderPolicy, outputLimits: WasmOutputLimits, };

export type WasmResolvedCitation = { sourceStart: number, sourceEnd: number, outcome: WasmCitationOutcome, };

export type WasmResolvedReference = { sourceStart: number, sourceEnd: number, outcome: WasmReferenceOutcome, };

export type WasmResolvedResource = { sourceStart: number, sourceEnd: number, outcome: WasmResourceOutcome, };

export type WasmResource = { sourceId: string, source: string, };

export type WasmResourceCapabilities = { images: boolean, media: boolean, };

export type WasmResourceFailureKind = "missing" | "outside-root" | "scheme-denied" | "permission-denied" | "media-type-unavailable" | "resolver-failure";

export type WasmResourceOutcome = { "status": "resolved", href: string, mediaType: string, byteLength: bigint | null, } | { "status": "failed", kind: WasmResourceFailureKind, };

export type WasmResourcePurpose = "image" | "icon" | "audio" | "video" | "video-poster";

export type WasmResourceQuery = { purpose: WasmResourcePurpose, form: WasmMacroForm, ownerRange: WasmTextRange, range: WasmTextRange, targetRange: WasmTextRange, target: string, };

export type WasmResponse = { packageVersion: string, version: number, generation: number, products: WasmProductSet, parse: ParseSummary, syntax: string, ast: string, html: string, attributeOccurrences: Array<WasmDocumentAttributeOccurrence>, attributeQueries: WasmAttributeQueryProduct, resourceQueries: Array<WasmResourceQuery>, diagnostics: Array<WasmDiagnostic>, renderDiagnostics: Array<WasmDiagnostic>, symbols: Array<WasmDocumentSymbol>, projection: WasmDocumentProjection | null, };

export type WasmRolePolicy = { allowed: Array<string>, unknown: WasmUnknownRole, };

export type WasmRuleSettings = { enabled: boolean, severity: WasmSeverity, };

export type WasmSafeMode = "unsafe" | "server" | "safe" | "secure";

export type WasmSearchTextKind = "prose" | "code";

export type WasmSearchTextSegment = { kind: WasmSearchTextKind, sourceRange: WasmTextRange, text: string, };

export type WasmSearchableText = { text: string, segments: Array<WasmSearchTextSegment>, };

export type WasmSectionKind = "document-title" | "part" | "section" | "appendix" | "discrete";

export type WasmSeverity = "error" | "warning" | "information" | "hint";

export type WasmSourceBlockProjection = { sourceRange: WasmTextRange, contentRange: WasmTextRange, title: WasmProjectedText | null, languageRange: WasmTextRange | null, language: string | null, lineNumbers: boolean, startLine: number | null, source: string, caption: string | null, };

export type WasmSourceLanguagePolicy = { allowed: Array<string> | null, unknown: WasmUnknownSourceLanguage, };

export type WasmSourceMapSegment = { outputStart: number, outputEnd: number, sourceId: string | null, sourceStart: number, sourceEnd: number, mapping: WasmSourceMapping, };

export type WasmSourceMapping = "identity" | "whole-origin";

export type WasmStructuredHeading = { kind: WasmSectionKind, level: number, id: string, idRange: WasmTextRange, title: string, range: WasmTextRange, titleRange: WasmTextRange, number: Array<number>, tocIncluded: boolean, };

export type WasmStylesheet = { "kind": "external", url: string, } | { "kind": "inline", css: string, };

export type WasmSymbolKind = "document-title" | "part" | "section" | "list-item";

export type WasmSyntaxMode = "permissive" | "strict";

export type WasmSyntaxOptions = { syntaxMode: WasmSyntaxMode, limits: WasmLimits, };

export type WasmTextEdit = { range: WasmTextRange, replacement: string, };

/**
 * A half-open UTF-8 byte range in the submitted source.
 */
export type WasmTextRange = { start: number, end: number, };

export type WasmTocEntry = { id: string, title: string, level: number, number: Array<number>, range: WasmTextRange, children: Array<WasmTocEntry>, };

export type WasmUnknownRole = "silent" | "diagnostic";

export type WasmUnknownSourceLanguage = "preserve-sanitized" | "omit-class" | "diagnostic";

export type WasmUnresolvedReferencePresentation = "target" | "label-only" | "hidden";
