// @generated by tools/generate-protocol.mjs from protocol/public-api.json; DO NOT EDIT.
export interface ProductSet {
  syntax?: boolean;
  canonicalAst?: boolean;
  html?: boolean;
  attributeOccurrences?: boolean;
  diagnostics?: boolean;
  symbols?: boolean;
  projection?: boolean;
}

export declare const PROTOCOL_SCHEMA_VERSION: 1;
export declare const PACKAGE_VERSION: "0.6.4";
export declare const PRODUCT_FIELDS: readonly ["syntax", "canonicalAst", "html", "attributeOccurrences", "diagnostics", "symbols", "projection"];
