// @generated by tools/generate-protocol.mjs from protocol/public-api.json; DO NOT EDIT.
export interface ProductSet {
  syntax: boolean;
  canonicalAst: boolean;
  html: boolean;
  attributeOccurrences: boolean;
  resourceQueries: boolean;
  diagnostics: boolean;
  symbols: boolean;
  projection: boolean;
}

export type Severity = "error" | "warning" | "information" | "hint";

export type SyntaxMode = "permissive" | "strict";

export type DocumentMode = "fragment" | "complete";

export type UnknownSourceLanguage = "preserve-sanitized" | "omit-class" | "diagnostic";

export type MathLanguage = "latex" | "typst";

export type UnresolvedReferencePresentation = "target" | "label-only" | "hidden";

export type StylesheetKind = "inline" | "external";

export type ReferenceStatus = "resolved" | "failed";

export type ReferenceFailureKind = "missing-target" | "missing-anchor" | "ambiguous-target" | "outside-root" | "resolver-failure";

export type ReferenceNotice = "fallback";

export type ResourceStatus = "resolved" | "failed";

export type ResourceFailureKind = "missing" | "outside-root" | "scheme-denied" | "permission-denied" | "media-type-unavailable" | "resolver-failure";

export type DocumentAttributeOperation = "set" | "unset";

export type ResourcePurpose = "image" | "icon" | "audio" | "video" | "video-poster";

export type MacroForm = "inline" | "block";

export type FormulaKind = "inline" | "block";

export type ReferenceTargetKind = "document-title" | "part" | "section" | "explicit-anchor" | "inline-anchor";

export type OrderedListStyle = "arabic" | "decimal" | "loweralpha" | "upperalpha" | "lowerroman" | "upperroman" | "lowergreek";

export type BlockPresentationKind = "admonition" | "quote" | "verse";

export type SectionKind = "document-title" | "part" | "section" | "appendix" | "discrete";

export type SearchTextKind = "prose" | "code";

export type Applicability = "always" | "maybe";

export type SymbolKind = "document-title" | "part" | "section" | "list-item";

export type SafeMode = "unsafe" | "server" | "safe" | "secure";

export type SourceMapping = "identity" | "whole-origin";

export interface AnalysisOptions {
  syntax?: SyntaxOptions;
  diagnostics?: DiagnosticProfile;
}

export interface SyntaxOptions {
  syntaxMode?: SyntaxMode;
  limits?: AnalysisLimits;
}

export interface DiagnosticProfile {
  protectedAttributes?: Record<string, string>;
  authoredUrls?: AuthoredUrlPolicy;
  maxDiagnostics?: number;
  rules?: Record<string, RuleSettings>;
}

export interface RuleSettings {
  enabled?: boolean;
  severity?: Severity;
}

export interface RenderPolicy {
  activeUrls?: ActiveUrlPolicy;
  externalLinks?: ExternalLinkPolicy;
  sourceLanguages?: SourceLanguagePolicy;
  mathLanguages?: MathLanguage[];
  unresolvedReferences?: UnresolvedReferencePresentation;
  resources?: ResourceCapabilities;
  documentMode?: DocumentMode;
  stylesheets?: Stylesheet[];
}

export interface OutputLimits {
  maxOutputBytes?: number;
}

export interface RenderInputs {
  references?: ResolvedReference[];
  resources?: ResolvedResource[];
}

export interface ResolvedReference {
  sourceStart: number;
  sourceEnd: number;
  outcome: ResolvedReferenceOutcome;
}

export interface ResolvedResource {
  sourceStart: number;
  sourceEnd: number;
  outcome: ResolvedResourceOutcome;
}

export interface AnalysisLimits {
  maxInputBytes?: number;
  maxLineBytes?: number;
  maxListDepth?: number;
  maxListContinuations?: number;
  maxBlockDepth?: number;
  maxInlineDepth?: number;
  maxFormulaBytes?: number;
  maxTableBytes?: number;
  maxTableCells?: number;
  maxTableColumns?: number;
  maxTableDepth?: number;
  maxCatalogEntries?: number;
  maxCatalogBytes?: number;
  maxBlocks?: number;
  maxNodes?: number;
  maxReferences?: number;
  maxAttributes?: number;
  maxAttributeExpansionDepth?: number;
  maxAttributeExpansionBytes?: number;
}

export interface AuthoredUrlPolicy {
  allowedSchemes?: string[];
  allowRelative?: boolean;
}

export interface ActiveUrlPolicy {
  allowedSchemes?: string[];
  allowAuthoredRelative?: boolean;
  allowResolvedRelative?: boolean;
  allowResolvedRootRelative?: boolean;
  allowDataUris?: boolean;
}

export interface ExternalLinkPolicy {
  openInNewContext?: boolean;
  noreferrer?: boolean;
}

export interface SourceLanguagePolicy {
  allowed?: string[] | null;
  unknown?: UnknownSourceLanguage;
}

export interface ResourceCapabilities {
  images?: boolean;
  media?: boolean;
}

export interface ParseSummary {
  packageVersion: string;
  blockCount: number;
  nodeCount: number;
  referenceCount: number;
}

export interface SourceBlockProjection {
  sourceRange: TextRange;
  contentRange: TextRange;
  languageRange: TextRange | null;
  language: string | null;
  source: string;
}

export interface FormulaProjection {
  kind: FormulaKind;
  language: MathLanguage;
  sourceRange: TextRange;
  contentRange: TextRange;
  source: string;
}

export interface ProjectedText {
  sourceRange: TextRange;
  text: string;
}

export interface ReferenceTarget {
  kind: ReferenceTargetKind;
  id: string;
  label: string;
  idRange: TextRange;
  targetRange: TextRange;
}

export interface ExternalLink {
  sourceRange: TextRange;
  targetRange: TextRange;
  target: string;
  label: string;
}

export interface ReferenceEdge {
  sourceId: string | null;
  sourceRange: TextRange;
  target: ReferenceKey;
  resolution: ResolvedReferenceOutcome | null;
}

export interface OrderedListProjection {
  sourceRange: TextRange;
  start: number | null;
  reversed: boolean;
  style: OrderedListStyle;
}

export interface BlockPresentationProjection {
  kind: BlockPresentationKind;
  sourceRange: TextRange;
  contentRange: TextRange;
  title: string | null;
  attribution: string | null;
  citation: string | null;
}

export interface DocumentStructure {
  headings: StructuredHeading[];
  toc: TocEntry[];
  manpage: Manpage | null;
}

export interface StructuredHeading {
  kind: SectionKind;
  level: number;
  id: string;
  idRange: TextRange;
  title: string;
  range: TextRange;
  titleRange: TextRange;
  number: number[];
  tocIncluded: boolean;
}

export interface TocEntry {
  id: string;
  title: string;
  level: number;
  number: number[];
  range: TextRange;
  children: TocEntry[];
}

export interface Manpage {
  name: string;
  section: string;
  purpose: string;
  titleRange: TextRange;
  nameRange: TextRange;
  purposeRange: TextRange;
}

export interface DocumentCatalogs {
  footnotes: Footnote[];
  bibliography: BibliographyEntry[];
  index: IndexEntry[];
}

export interface Footnote {
  number: number;
  id: string | null;
  definitionRange: TextRange;
  contentRange: TextRange;
  text: string;
  occurrences: TextRange[];
}

export interface BibliographyEntry {
  id: string;
  definitionRange: TextRange;
  references: TextRange[];
}

export interface IndexEntry {
  terms: string[];
  display: string;
  occurrences: TextRange[];
}

export interface SearchableText {
  text: string;
  segments: SearchTextSegment[];
}

export interface SearchTextSegment {
  kind: SearchTextKind;
  sourceRange: TextRange;
  text: string;
}

export interface DocumentSymbol {
  name: string;
  kind: SymbolKind;
  range: TextRange;
  selectionRange: TextRange;
  children: DocumentSymbol[];
}

export interface PreprocessResource {
  sourceId: string;
  source: string;
}

export interface PreprocessOptions {
  baseUri?: string | null;
  safeMode?: SafeMode;
  allowedSchemes?: string[];
  attributes?: Record<string, string>;
  enableIncludes?: boolean;
  maxIncludeDepth?: number;
  maxIncludes?: number;
  maxTotalBytes?: number;
  maxExpandedNodes?: number;
  maxSourceMapSegments?: number;
}

export interface PreprocessResponse {
  packageVersion: string;
  source: string;
  sourceMap: SourceMapSegment[];
}

export interface SourceMapSegment {
  outputStart: number;
  outputEnd: number;
  sourceId: string | null;
  sourceStart: number;
  sourceEnd: number;
  mapping: SourceMapping;
}

export interface WasmError {
  code: string;
  message: string;
}

export type Stylesheet =
  | { kind: "inline"; css: string }
  | { kind: "external"; url: string };

export type ResolvedReferenceOutcome =
  | { status: "resolved"; href: string; displayText?: string | null; notices?: ReferenceNotice[] }
  | { status: "failed"; kind: ReferenceFailureKind };

export type ResolvedResourceOutcome =
  | { status: "resolved"; href: string; mediaType: string; byteLength?: number | null }
  | { status: "failed"; kind: ResourceFailureKind };

export type ReferenceKey =
  | { kind: "local"; anchor: string }
  | { kind: "document"; document: string; anchor: string | null }
  | { kind: "scheme"; scheme: string; locator: string; anchor: string | null };

export interface TextRange {
  start: number;
  end: number;
}

export interface Diagnostic {
  id: string;
  code: string;
  severity: Severity;
  message: string;
  range: TextRange;
  related: RelatedInformation[];
  fixes: Fix[];
}

export interface RelatedInformation {
  range: TextRange;
  message: string;
}

export interface TextEdit {
  range: TextRange;
  replacement: string;
}

export interface Fix {
  title: string;
  applicability: Applicability;
  edits: TextEdit[];
}

export interface DocumentProjection {
  packageVersion: string;
  sourceId: string | null;
  sourceBlocks: SourceBlockProjection[];
  formulas: FormulaProjection[];
  blockPresentations: BlockPresentationProjection[];
  orderedLists: OrderedListProjection[];
  referenceEdges: ReferenceEdge[];
  externalLinks: ExternalLink[];
  searchableText: SearchableText;
  structure: DocumentStructure;
  catalogs: DocumentCatalogs;
  targets: ReferenceTarget[];
  title: ProjectedText | null;
}

export interface DocumentAttributeOccurrence {
  range: TextRange;
  nameRange: TextRange;
  valueRange: TextRange;
  name: string;
  rawValue: string;
  operation: DocumentAttributeOperation;
}

export interface ResourceQuery {
  purpose: ResourcePurpose;
  form: MacroForm;
  ownerRange: TextRange;
  range: TextRange;
  targetRange: TextRange;
  target: string;
}

export interface WasmRequest {
  packageVersion: string;
  sourceId?: string | null;
  version: number;
  generation: number;
  source: string;
  products?: ProductSet;
  renderInputs?: RenderInputs;
  analysisOptions?: AnalysisOptions;
  renderPolicy?: RenderPolicy;
  outputLimits?: OutputLimits;
}

export interface PreprocessRequest {
  packageVersion: string;
  sourceId?: string | null;
  source: string;
  resources?: Record<string, PreprocessResource>;
  options?: PreprocessOptions;
}

export interface UpdateRequest {
  sourceId?: string | null;
  version: number;
  source: string;
  products?: ProductSet;
  renderInputs?: RenderInputs;
  analysisOptions?: AnalysisOptions;
  renderPolicy?: RenderPolicy;
  outputLimits?: OutputLimits;
}

export interface AdocWeaveWasmResponse {
  packageVersion: string;
  version: number;
  generation: number;
  products: Required<ProductSet>;
  parse: ParseSummary;
  syntax: string;
  ast: string;
  html: string;
  attributeOccurrences: DocumentAttributeOccurrence[];
  resourceQueries: ResourceQuery[];
  diagnostics: Diagnostic[];
  renderDiagnostics: Diagnostic[];
  symbols: DocumentSymbol[];
  projection: DocumentProjection;
}

export type WorkerRequest =
  | { type: "initialize"; protocolVersion: number; moduleUrl: string; wasmUrl: string; debounceMs: number; cancellationBuffer: SharedArrayBuffer | null }
  | { type: "analyze"; protocolVersion: number; version: number; generation: number; payload: WasmRequest };

export type WorkerResponse =
  | { type: "ready"; protocolVersion: number }
  | { type: "result"; protocolVersion: number; version: number; generation: number; result: AdocWeaveWasmResponse }
  | { type: "error"; protocolVersion: number; version: number; generation: number; error: WasmError };

export interface AdocWeaveError {
  code: string;
  message: string;
  sourceVersion: number | null;
  generation: number;
}

export declare const PROTOCOL_SCHEMA_VERSION: 3;
export declare const WORKER_PROTOCOL_VERSION: 1;
export declare const PACKAGE_VERSION: "0.11.0";
export declare const PRODUCT_FIELDS: readonly ["syntax", "canonicalAst", "html", "attributeOccurrences", "resourceQueries", "diagnostics", "symbols", "projection"];
export declare const REQUEST_FIELDS: readonly ["packageVersion", "sourceId", "version", "generation", "source", "products", "renderInputs", "analysisOptions", "renderPolicy", "outputLimits"];
export declare const REQUEST_ENUMS: { readonly "Severity": readonly ["error", "warning", "information", "hint"]; readonly "SyntaxMode": readonly ["permissive", "strict"]; readonly "DocumentMode": readonly ["fragment", "complete"]; readonly "UnknownSourceLanguage": readonly ["preserve-sanitized", "omit-class", "diagnostic"]; readonly "MathLanguage": readonly ["latex", "typst"]; readonly "UnresolvedReferencePresentation": readonly ["target", "label-only", "hidden"]; readonly "StylesheetKind": readonly ["inline", "external"]; readonly "ReferenceStatus": readonly ["resolved", "failed"]; readonly "ReferenceFailureKind": readonly ["missing-target", "missing-anchor", "ambiguous-target", "outside-root", "resolver-failure"]; readonly "ReferenceNotice": readonly ["fallback"]; readonly "ResourceStatus": readonly ["resolved", "failed"]; readonly "ResourceFailureKind": readonly ["missing", "outside-root", "scheme-denied", "permission-denied", "media-type-unavailable", "resolver-failure"] };
export declare const WORKER_MESSAGE_FIELDS: { readonly "requests.initialize": readonly ["type", "protocolVersion", "moduleUrl", "wasmUrl", "debounceMs", "cancellationBuffer"]; readonly "requests.analyze": readonly ["type", "protocolVersion", "version", "generation", "payload"]; readonly "responses.ready": readonly ["type", "protocolVersion"]; readonly "responses.result": readonly ["type", "protocolVersion", "version", "generation", "result"]; readonly "responses.error": readonly ["type", "protocolVersion", "version", "generation", "error"] };
